Repository googleapis/api-common-java, pull requests merged in 2020-05, with the labels that each got.

#125 chore: support complex resource identifiers
  src/main/java/com/google/api/pathtemplate/PathTemplate.java
  src/test/java/com/google/api/pathtemplate/PathTemplateTest.java
Labels: cla: yes, kokoro:force-run

#138 deps: update guava
  build.gradle
Labels: cla: yes

#142 deps: stay away from Guava JRE
  renovate.json
Labels: cla: yes, semver: patch

#143 Release docs for 1.9.0
  1.9.0/apidocs/allclasses-frame.html
  1.9.0/apidocs/allclasses-noframe.html
  1.9.0/apidocs/com/google/api/core/AbstractApiFuture.html
  1.9.0/apidocs/com/google/api/core/AbstractApiService.html
  1.9.0/apidocs/com/google/api/core/ApiAsyncFunction.html
  1.9.0/apidocs/com/google/api/core/ApiClock.html
  1.9.0/apidocs/com/google/api/core/ApiFunction.html
  1.9.0/apidocs/com/google/api/core/ApiFuture.html
  1.9.0/apidocs/com/google/api/core/ApiFutureCallback.html
  1.9.0/apidocs/com/google/api/core/ApiFutureToListenableFuture.html
  1.9.0/apidocs/com/google/api/core/ApiFutures.html
  1.9.0/apidocs/com/google/api/core/ApiService.Listener.html
  1.9.0/apidocs/com/google/api/core/ApiService.State.html
  1.9.0/apidocs/com/google/api/core/ApiService.html
  1.9.0/apidocs/com/google/api/core/BetaApi.html
  1.9.0/apidocs/com/google/api/core/CurrentMillisClock.html
  1.9.0/apidocs/com/google/api/core/ForwardingApiFuture.html
  1.9.0/apidocs/com/google/api/core/InternalApi.html
  1.9.0/apidocs/com/google/api/core/InternalExtensionOnly.html
  1.9.0/apidocs/com/google/api/core/ListenableFutureToApiFuture.html
  1.9.0/apidocs/com/google/api/core/NanoClock.html
  1.9.0/apidocs/com/google/api/core/SettableApiFuture.html
  1.9.0/apidocs/com/google/api/core/package-frame.html
  1.9.0/apidocs/com/google/api/core/package-summary.html
  1.9.0/apidocs/com/google/api/core/package-tree.html
  1.9.0/apidocs/com/google/api/pathtemplate/PathTemplate.html
  1.9.0/apidocs/com/google/api/pathtemplate/TemplatedResourceName.Resolver.html
  1.9.0/apidocs/com/google/api/pathtemplate/TemplatedResourceName.html
  1.9.0/apidocs/com/google/api/pathtemplate/ValidationException.Supplier.html
  1.9.0/apidocs/com/google/api/pathtemplate/ValidationException.html
  1.9.0/apidocs/com/google/api/pathtemplate/package-frame.html
  1.9.0/apidocs/com/google/api/pathtemplate/package-summary.html
  1.9.0/apidocs/com/google/api/pathtemplate/package-tree.html
  1.9.0/apidocs/com/google/api/resourcenames/ResourceName.html
  1.9.0/apidocs/com/google/api/resourcenames/ResourceNameFactory.html
  1.9.0/apidocs/com/google/api/resourcenames/UntypedResourceName.html
  1.9.0/apidocs/com/google/api/resourcenames/package-frame.html
  1.9.0/apidocs/com/google/api/resourcenames/package-summary.html
  1.9.0/apidocs/com/google/api/resourcenames/package-tree.html
  1.9.0/apidocs/constant-values.html
  1.9.0/apidocs/deprecated-list.html
  1.9.0/apidocs/help-doc.html
  1.9.0/apidocs/index-all.html
  1.9.0/apidocs/index.html
  1.9.0/apidocs/overview-frame.html
  1.9.0/apidocs/overview-summary.html
  1.9.0/apidocs/overview-tree.html
  1.9.0/apidocs/package-list
  1.9.0/apidocs/script.js
  1.9.0/apidocs/serialized-form.html
  1.9.0/apidocs/stylesheet.css
  apidocs/index.html
Labels: cla: yes

#144 chore: release v1.9.1
  version.txt
Labels: cla: yes

#146 fix: update mockito dependency
  build.gradle
Labels: cla: yes
