Repository googleapis/api-common-java, pull requests merged in 2021-09, with the labels that each got.

#274 chore: remove readme autosynth config
  .github/readme/synth.py
  .kokoro/continuous/readme.cfg
Labels: kokoro:force-run, cla: yes, automerge

#275 chore: update java docfx doclet version
  build.gradle
Labels: cla: yes

#276 chore: update java-docfx-doclet version
  build.gradle
Labels: cla: yes

#282 chore: change branch master to main in sync-repo-settings.yaml
  .github/sync-repo-settings.yaml
Labels: cla: yes, automerge

#283 chore: change branch master to main in github configurations
  .github/blunderbuss.yml
  .github/workflows/ci.yaml
  README.md
Labels: cla: yes, automerge
